# Generated by Django 4.1 on 2022-09-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room", old_name="guest_can_pause", new_name="can_guest_pause",
        ),
    ]
